### PR TITLE
Add missing prereqs

### LINKED ISSUE #47: Missing Pre-requisities
When running the quickstart script I found some missing per-requisities programs.

- kind https://github.com/kubernetes-sigs/kind
- clusteradm https://github.com/open-cluster-management-io/clusteradm
   -  newest version v0.8 does not work with the quickstart but older v0.7.2 does

### PR DESCRIPTION
**Pull request by david-martin**
Fixes #47

### CODE REVIEW

**Review by azgabur — APPROVED** [review]

**Comment by jasonmadigan** [comment]
We could probably just patch .quickstartEnv to use `dockerBinCmd` - clusteradm and yq are installed in the `quay.io/kuadrant/mgc-tools:latest` image (one or two less pre-reqs?)

**Comment by david-martin** [comment]
> We could probably just patch .quickstartEnv to use `dockerBinCmd` for `clusteradm`. It's installed in the `quay.io/kuadrant/mgc-tools:latest` image (one less pre-req?)

i'll give this a spin

**Comment by david-martin** [comment]
@jasonmadigan updated with clusteradm from docker.
Works locally.
yq from docker makes less sense since the user has to follow steps that include yq later in the guide

**Comment by jasonmadigan** [comment]
lgtm

**Pull request merged**
